<?php

$pageTitle = 'Delete task';
$url   = $this->url('task', ['action' => 'delete', 'id' => $id]);

$this->headTitle($pageTitle);
?>
<h1><?= $this->escapeHtml($pageTitle) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($task->title) ?>" by
    "<?= $this->escapeHtml($task->artist) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $task->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>