<?php
// module/Task/view/task/task/index.phtml:

$title = 'My Tasks';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="btn btn-primary" href="<?= $this->url('task', ['action' => 'add']) ?>">Add new task</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Create at</th>
    <th>Last Update</th>
    <th>Actions</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($tasks as $task) : ?>
    <tr>
        <td><?= $this->escapeHtml($task->title) ?></td>
        <td><?= $this->escapeHtml($task->description) ?></td>
        <td><?= $this->escapeHtml($task->status) ?></td>
        <td><?= $this->escapeHtml($task->create_at) ?></td>
        <td><?= $this->escapeHtml($task->update_at) ?></td>
        <?if($task->status === 'pending'):?>
            <td>
                <a class="btn btn-success" href="<?= $this->url('task', ['action' => 'edit', 'id' => $task->id]) ?>">Edit</a>
                <a class="btn btn-danger" href="<?= $this->url('task', ['action' => 'delete', 'id' => $task->id]) ?>">Delete</a>
            </td>
        <?else:?>
            <td>
                <a class="btn btn-success disabled" href="<?= $this->url('task', ['action' => 'edit', 'id' => $task->id]) ?>">Edit</a>
                <a class="btn btn-danger disabled" href="<?= $this->url('task', ['action' => 'delete', 'id' => $task->id]) ?>">Delete</a>
            </td>
        <?endif?>
    </tr>
<?php endforeach; ?>
</table>